### ISSUE TITLE
The instructions are not quite sufficient to get it working for me.

### ISSUE THREAD

**Issue by rlamoni** [Ivoirians/ohhell-scorekeeper#1]
Everything installs ok and `npm run dev` works with two warnings an no errors.  `http://localhost:8080/webpack-dev-server/` also looks good (no errors).  But, the /ohHell.js file (/scripts/ohHell.js) is not found.  I does appear to be be being compiled (see output).  But, it must be going into memory and not on the file system since I cannot find it anywhere.

```
npm run dev
```
```
> ohhellscorekeeper@1.0.0 dev c:\andrew\ohhell-scorekeeper
> webpack-dev-server --config webpack/webpack-dev.config.js --content-base public/ --watch --hot

Project is running at http://localhost:8080/
webpack output is served from /scripts/
Content not from webpack is served from c:\andrew\ohhell-scorekeeper\public
(node:8320) DeprecationWarning: loaderUtils.parseQuery() received a non-string value which can be problematic, see https://github.com/webpack/loader-utils/issues/56
parseQuery() will be replaced with getOptions() in the next major version of loader-utils.
Hash: ac55cfa134d0adf4adc8
Version: webpack 2.2.1
Time: 6001ms
     Asset     Size  Chunks                    Chunk Names
/ohHell.js  1.45 MB       0  [emitted]  [big]  main
chunk    {0} /ohHell.js (main) 1.38 MB [entry] [rendered]
   [22] ./~/react-dom/index.js 59 bytes {0} [built]
   [24] ./~/react/react.js 56 bytes {0} [built]
   [25] ./src/scripts/pageEnum.jsx 544 bytes {0} [built]
  [127] (webpack)-dev-server/client?http://localhost:8080 5.28 kB {0} [built]
  [128] ./src/scripts/ohHell.jsx 6.96 kB {0} [built]
  [129] ./~/webpack/hot/dev-server.js 1.85 kB {0} [built]
  [130] (webpack)-dev-server/client/overlay.js 3.6 kB {0} [built]
  [177] (webpack)/~/url/url.js 23.3 kB {0} [built]
  [184] ./src/scripts/createGame.jsx 8.97 kB {0} [built]
  [185] ./src/scripts/mainMenu.jsx 5.19 kB {0} [built]
  [186] ./src/scripts/roundBids.jsx 7.04 kB {0} [built]
  [187] ./src/scripts/roundTricks.jsx 8.52 kB {0} [built]
  [188] ./src/scripts/statistics.jsx 2.77 kB {0} [built]
  [189] ./src/scripts/winScreen.jsx 3.45 kB {0} [built]
  [292] multi (webpack)-dev-server/client?http://localhost:8080 webpack/hot/dev-server ./src/scripts/ohHell.jsx 52 bytes {0} [built]
     + 278 hidden modules

WARNING in (webpack)/buildin/global.js
There are multiple modules with names that only differ in casing.
This can lead to unexpected behavior when compiling on a filesystem with other case-semantic.
Use equal casing. Compare these module identifiers:
* C:\Program Files\nodejs\node_modules\webpack\buildin\global.js
    Used by 22 module(s), i. e.
    C:\Program Files\nodejs\node_modules\webpack-dev-server\node_modules\sockjs-client\lib\entry.js
* c:\Program Files\nodejs\node_modules\webpack\buildin\global.js
    Used by 6 module(s), i. e.
    c:\andrew\ohhell-scorekeeper\node_modules\Enum\dist\enum.js

WARNING in (webpack)/~/process/browser.js
There are multiple modules with names that only differ in casing.
This can lead to unexpected behavior when compiling on a filesystem with other case-semantic.
Use equal casing. Compare these module identifiers:
* C:\Program Files\nodejs\node_modules\webpack\node_modules\process\browser.js
    Used by 21 module(s), i. e.
    C:\Program Files\nodejs\node_modules\webpack-dev-server\node_modules\sockjs-client\lib\main.js
* c:\Program Files\nodejs\node_modules\webpack\node_modules\process\browser.js
    Used by 80 module(s), i. e.
    c:\andrew\ohhell-scorekeeper\node_modules\react-dom\lib\ReactDOM.js
webpack: Compiled with warnings.
```

I am running nodejs version 7.6.0 and npm version 4.1.2 if that helps.

**Comment by rlamoni** [comment]
@Ivoirians, ideas?

**Comment by Ivoirians** [comment]
Yes, it was weird to me at first, but npm run dev uses webpack-dev-server which serves the js file from memory. You should still be able to view the page with correct behavior at localhost. If you can't, in the meantime you should be able to run npm run build and have the file placed in the correct spot.

I'll look into these warnings.

**Comment by Ivoirians** [comment]
I guess to make sure we're on the same page: is the app working at https://localhost:8080 and you're only looking for ohhell.js, or are you getting a 404 when you try to use the local app?

**Comment by rlamoni** [comment]
The app runs and index.html is served properly.  But, `http://localhost:8080/scripts/ohHell.js` 404's so the app doesn't work.

**Comment by psivanov** [comment]
Same here.
Except, I don't have warnings and the output of "npm run dev" is slightly different.

https://localhost:8080/ is 404 but 
http://localhost:8080/ returns:


<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="Cache-control" content="no-cache">
    <title>Oh Hell</title>
	<link rel="stylesheet" type="text/css" href="css/ohhell.css">
	<link href="https://fonts.googleapis.com/css?family=Titillium+Web" rel="stylesheet">
  </head>
  <body>
  	<div id='root'> </div>
    <script src="scripts/ohHell.js"></script>
  </body>
</html>

but scripts/ohHell.js is also 404

**Comment by rlamoni** [comment]
I'm guessing HTTPS will not work since you cannot get a cert for localhost and port 8080 is seems to be listening for HTTP not HTTPS.  But, it sounds like @psivanov  and I have the same problem.  There's something that is not routing correctly.

**Comment by psivanov** [comment]
it works after npm run build though

**Comment by Ivoirians** [comment]
That's a little odd. So if you run npm run build once and then npm run dev, does it still handle hot reloading after you make an obvious change to mainMenu.jsx? If not, it seems like there's a webpack config issue, specifically, the publicPath param isn't working. But we should all be on the same page there...

**Comment by Ivoirians** [comment]
I'm going to try a completely clean install on a machine I haven't touched before. (my rdev, ha)

**Comment by rlamoni** [comment]
After doing a build the app works fine.  Also, when I change a jsx files some kind of recompile-activity happens on the console that is running the server. But, it doesn't appear that my running version of the app sees these changes.  This implies that the routing is still not working, it is just grabbing the static version of the built file each time.

**Comment by psivanov** [comment]
Confirmed what @rlamoni said.

**Comment by Ivoirians** [comment]
Yeah, I just encountered the same issue on RDEV. I'll probably need the rest of the night to figure it out, since the webpack versions agree, they're using the same config, everything looks functionally identical. Sorry for the inconvenience

**Comment by psivanov** [comment]
Interestingly, the new game button also doesn't work for me. @Ivoirians, is everything pushed?

**Comment by Ivoirians** [comment]
Yep, the prod app should mirror the existing app. You should be getting a console error? Maybe firebase related?

It looks like the issue is the config syntax doesn't work in webpack 2. I had webpack 1.14.0 installed on each of my machines that worked. So the fix will be updating the webpack config using [this guide](http://javascriptplayground.com/blog/2016/10/moving-to-webpack-2/) (pretty straightforward).

**Comment by Ivoirians** [comment]
What an ordeal. The error was a single slash in the publicPath parameter. I've verified things work now--you should only need to pull the latest configs and npm run dev should work.

**Comment by psivanov** [comment]
It works better now, but I still need to refresh the page after source file change.
Something is not quite working with hot module reload.

**Comment by Ivoirians** [comment]
Ah, sorry if I implied hot reloading was set up--it isn't. Refreshing the page to see changes is the best I've got so far.

Someone would need to set up [this](http://webpack.github.io/docs/hot-module-replacement-with-webpack.html). I've just been using the Resume feature to more-or-less preserve the state of a game between reloads.
