### ISSUE TITLE
Deploy failed

### ISSUE THREAD

**Issue by psivanov** [Ivoirians/ohhell-scorekeeper#2]
I tried to deploy my commit, but I think I broke the app in a strange way...

Rollback doesn't work, so not sure how to fix.

I noticed that 'npm run deploy' deploys even if the build failed.
For some reason the first time I tried, the build failed (even though 'npm run dev' was fine).
Then I ran 'npm install' and this (I think) fixed the build.
Then I deployed the good build, but no dice.

**Comment by Ivoirians** [comment]
It looks like it deployed correctly? Sometimes there's a delay, maybe only the first time a user deploys to a project. Or you fixed it. Either way, npm run deploy probably shouldn't deploy if the build step fails.

Also, nice commit!
